SET(BM3D_MODULE_NAME_TMP2 ${BM3D_MODULE_NAME})
SET(BM3D_MODULE_NAME ${BM3D_MODULE_NAME}/RRT)
BM3D_SRC_SUBDIR_PROCESS(

HRICS_rrt.cpp
HRICS_rrtExpansion.cpp

HRICS_rrtPlan.cpp
HRICS_rrtPlanExpansion.cpp

)

BM3D_INC_DIR_PROCESS (${BM3D_MODULE_NAME})

#include(${CMAKE_SOURCE_DIR}/${BM3D_MODULE_NAME}/SourceList.cmake)
SET(BM3D_MODULE_NAME ${BM3D_MODULE_NAME_TMP2})
