SET(BM3D_MODULE_NAME_TMP ${BM3D_MODULE_NAME})
SET(BM3D_MODULE_NAME ${BM3D_MODULE_NAME}/PRM)
BM3D_INC_DIR_PROCESS (${BM3D_MODULE_NAME})
BM3D_SRC_SUBDIR_PROCESS(
ACR.cpp
PRM.cpp 
sPRM.cpp
Visibility.cpp
PerturbationRoadmap.cpp)
SET(BM3D_MODULE_NAME ${BM3D_MODULE_NAME_TMP})


