SET(BM3D_MODULE_NAME_TMP2 ${BM3D_MODULE_NAME})
SET(BM3D_MODULE_NAME ${BM3D_MODULE_NAME}/RRT-Variants)
BM3D_INC_DIR_PROCESS (${BM3D_MODULE_NAME})
BM3D_SRC_SUBDIR_PROCESS(
ManhattanLike-RRT.cpp 
Transition-RRT.cpp
Multi-RRT.cpp
Multi-TRRT.cpp
Threshold-RRT.cpp
Star-RRT.cpp
Costmap-RRT.cpp
)
SET(BM3D_MODULE_NAME ${BM3D_MODULE_NAME_TMP2})
