SET(BM3D_MODULE_NAME_TMP2 ${BM3D_MODULE_NAME})
SET(BM3D_MODULE_NAME ${BM3D_MODULE_NAME}/Grid)
BM3D_SRC_SUBDIR_PROCESS(

HRICS_Cell.cpp
HRICS_Grid.cpp
HRICS_GridState.cpp
HRICS_TwoDGrid.cpp
HRICS_NaturalGrid.cpp
HRICS_NaturalCell.cpp
HRICS_RobotBaseGrid.cpp
HRICS_EnvGrid.cpp

)

BM3D_INC_DIR_PROCESS (${BM3D_MODULE_NAME})

include_directories (${BM3D_MODULE_NAME})
SET(BM3D_MODULE_NAME ${BM3D_MODULE_NAME_TMP2})
